apps/blog_web/lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", BlogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/session", SessionController, only: [:new, :create, :delete]
    resources "/registration", RegistrationController, only: [:new, :create]
    resources "/hubs", HubController, only: [:new, :index, :create]
    resources "/posts", PostController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  scope "/api", BlogWeb.Api do
    pipe_through :api
    resources "/hubs", HubController, only: [:index]
    resources "/comments", CommentController, except: [:new, :edit]
  end

  scope "/admin" do
    pipe_through :browser
    forward "/", AdminWeb.Endpoint, namespace: "admin"
  end
end

apps/blog_web/lib/blog_web/subdomain_router.ex
defmodule BlogWeb.SubdomainRouter do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", BlogWeb, as: :sub do
    pipe_through :browser # Use the default browser stack

#    resources "/hubs", HubController, only: [:new, :create]
    get "/", HubController, :show
    get "/edit", HubController, :edit
    put "/", HubController, :update
    delete "/", HubController, :delete

    resources "/session", SessionController, only: [:new, :create, :delete]
    resources "/registration", RegistrationController, only: [:new, :create]

    resources "/posts", PostController, only: [:show, :new, :create, :edit, :update, :delete]
  end

  # Other scopes may use custom stacks.
#  scope "/api", BlogWeb.Api do
#    pipe_through :api
#    resources "/hubs", HubController, only: [:index]
#  end
end

apps/blog_web/lib/blog_web/views/shared_view.ex
defmodule BlogWeb.SharedView do
  use BlogWeb, :view
end

apps/blog_web/lib/blog_web/templates/shared/post_cut.html.eex
<div class="post-list">
  <div class="post-header">
    <h3><%= @post.title %></h3>
  </div>
  <div class="post-body">
    <%= raw BlogWeb.LayoutView.sanitize(@post.cut)%>
  </div>
  <div class="post-footer">
    <div class="float-right">
      <div class="btn-group">
        <span class="text">
          Написал:
          <%= @post.created_by.username %>
        </span>
      </div>
      <div class="btn-group">
        <span class="text">
          <%= @post.inserted_at |> BlogWeb.LayoutView.date_to_string %>
        </span>
      </div>
      <div class="btn-group">
        <%= link "Комментировать", to: to_subdomain(sub_post_url(@conn, :show, @post.slug), @post.hub), class: "btn btn-sm btn-light" %>
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
          <div class="dropdown-menu">
            <%= if Blog.Posts.editable?(@post, @current_user) do %>
              <%= link "Редактировать", to: to_subdomain(sub_post_url(@conn, :edit, @post.slug), @post.hub), class: "dropdown-item" %>
            <% end %>
            <%= if Blog.Posts.deletable?(@post, @current_user) do %>
              <%= link "Удалить", to: to_subdomain(sub_post_url(@conn, :edit, @post.slug), @post.hub), class: "dropdown-item" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>