apps/blog_web/lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", BlogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/session", SessionController, only: [:new, :create, :delete]
    resources "/registration", RegistrationController, only: [:new, :create]
    resources "/hubs", HubController, only: [:new, :index, :create]
    resources "/posts", PostController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  scope "/api", BlogWeb.Api do
    pipe_through :api
    resources "/hubs", HubController, only: [:index]
    resources "/comments", CommentController, except: [:new, :edit]
  end

  scope "/admin" do
    pipe_through :browser
    forward "/", AdminWeb.Endpoint, namespace: "admin"
  end
end

apps/blog_web/lib/blog_web/subdomain_router.ex
defmodule BlogWeb.SubdomainRouter do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", BlogWeb, as: :sub do
    pipe_through :browser # Use the default browser stack

#    resources "/hubs", HubController, only: [:new, :create]
    get "/", HubController, :show
    get "/edit", HubController, :edit
    put "/", HubController, :update
    delete "/", HubController, :delete

    resources "/session", SessionController, only: [:new, :create, :delete]
    resources "/registration", RegistrationController, only: [:new, :create]

    resources "/posts", PostController, only: [:show, :new, :create, :edit, :update, :delete]
  end

  # Other scopes may use custom stacks.
#  scope "/api", BlogWeb.Api do
#    pipe_through :api
#    resources "/hubs", HubController, only: [:index]
#  end
end

apps/blog_web/lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view

  def is_preloaded(model, assoc) do
    case Map.get(model, assoc) do
      %Ecto.Association.NotLoaded{} -> false
      _ -> true
    end
  end

  def date_to_string(date) do
    date_now = NaiveDateTime.utc_now |> Calendar.Strftime.strftime!("%Y-%m-%d")
    date_tommorow = NaiveDateTime.utc_now |> NaiveDateTime.add(-1 * 60*60*24) |> Calendar.Strftime.strftime!("%Y-%m-%d")

    cond do
      Calendar.Strftime.strftime!(date, "%Y-%m-%d") == date_now ->
        "Сегодня #{Calendar.Strftime.strftime!(date, "%H:%M")}"
      Calendar.Strftime.strftime!(date, "%Y-%m-%d") == date_tommorow ->
        "Вчера #{Calendar.Strftime.strftime!(date, "%H:%M")}"
      true ->
        Calendar.Strftime.strftime!(date, "%Y-%m-%d %H:%M")
    end
  end

  def sanitize(html) do
    html |> HtmlSanitizeEx.Scrubber.scrub(BlogWeb.Sanitizers.BasicHTML)
  end
end

apps/blog_web/lib/blog_web/templates/layout/_navbar.html.eex
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <%= if logged?(@conn) do %>
          <li class="nav-item">
            <%= link "Создать пост", to: post_path(@conn, :new), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Создать хаб", to: hub_path(@conn, :new), class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link "Список хабов", to: hub_url(@conn, :index), class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <%= if logged?(@conn) do %>
          <li class="nav-item">
            <%= link current_user(@conn).username, to: "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Выйти", to: session_path(@conn, :delete, "me"), class: "nav-link", method: "delete" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link "Войти", to: session_path(@conn, :new), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Регистрация", to: registration_path(@conn, :new), class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

<%= if get_flash(@conn, :info) do %>
  <div class="alert alert-info" role="alert">
    <%= get_flash(@conn, :info) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<%= if get_flash(@conn, :error) do %>
  <div class="alert alert-danger" role="alert">
    <%= get_flash(@conn, :error) %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

apps/blog_web/lib/blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <div class="container-fluid">
      <%= render "_navbar.html", assigns %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>